name: Zola build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_only:
    name: Build only
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Zola build
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          CHECK_LINKS: true
          BUILD_DIR: .
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Zola build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

